/**
 * Tests for GitHub integration
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import {
  generatePrCommentBody,
  detectPrNumber,
  detectRepository,
  isGitHubActionsEnvironment,
} from '../../../src/output/github.js'
import type { ViolationReport, Violation } from '../../../src/enforcer/violations.js'

function createMockReport(violations: Violation[] = []): ViolationReport {
  const counts = {
    flow: 0,
    isolation: 0,
    circular: 0,
    unmapped: 0,
    unlayered: 0,
    orphan: 0,
    depth: 0,
    publicApi: 0,
    dependentBudget: 0,
    importCount: 0,
    total: 0,
  }

  let errorCount = 0
  let warnCount = 0

  for (const v of violations) {
    if (v.type === 'flow') counts.flow++
    if (v.type === 'isolation') counts.isolation++
    if (v.type === 'circular') counts.circular++
    if (v.type === 'unmapped') counts.unmapped++
    if (v.type === 'unlayered') counts.unlayered++
    if (v.type === 'orphan') counts.orphan++
    if (v.type === 'depth') counts.depth++
    if (v.type === 'publicApi') counts.publicApi++
    if (v.type === 'dependentBudget') counts.dependentBudget++
    if (v.type === 'importCount') counts.importCount++

    if (v.severity === 'error') errorCount++
    if (v.severity === 'warn') warnCount++
    counts.total++
  }

  return {
    violations,
    counts,
    severityCounts: {
      error: errorCount,
      warn: warnCount,
    },
    passed: errorCount === 0,
  }
}

function createMockViolation(overrides: Partial<Violation> = {}): Violation {
  return {
    type: 'flow',
    severity: 'error',
    message: 'Test violation',
    sourceFile: 'src/test.ts',
    targetFile: 'src/other.ts',
    sourceLayer: 'feature',
    targetLayer: 'core',
    ...overrides,
  }
}

describe('generatePrCommentBody', () => {
  it('generates markdown with passed status', () => {
    const report = createMockReport([])
    const body = generatePrCommentBody(report)

    expect(body).toContain('## Layerguard Architecture Check')
    expect(body).toContain('✅ Passed')
  })

  it('generates markdown with failed status', () => {
    const report = createMockReport([createMockViolation()])
    const body = generatePrCommentBody(report)

    expect(body).toContain('❌ Failed')
  })

  it('includes summary table', () => {
    const report = createMockReport([createMockViolation()])
    const body = generatePrCommentBody(report)

    expect(body).toContain('| Metric | Count |')
    expect(body).toContain('| Errors |')
    expect(body).toContain('| Total Violations |')
  })

  it('includes violations by type with emojis', () => {
    const report = createMockReport([
      createMockViolation({ type: 'flow' }),
      createMockViolation({ type: 'circular' }),
    ])
    const body = generatePrCommentBody(report)

    expect(body).toContain('Violations by Type')
    expect(body).toContain('🚫') // flow emoji
    expect(body).toContain('🔄') // circular emoji
    expect(body).toContain('**flow**')
    expect(body).toContain('**circular**')
  })

  it('includes top violations in collapsible details', () => {
    const report = createMockReport([
      createMockViolation({
        sourceFile: 'src/test.ts',
        line: 10,
        message: 'Test violation',
      }),
    ])
    const body = generatePrCommentBody(report, { showDetails: true })

    expect(body).toContain('<details>')
    expect(body).toContain('Top Violations')
    expect(body).toContain('`src/test.ts:10`')
    expect(body).toContain('Test violation')
    expect(body).toContain('</details>')
  })

  it('hides details when showDetails is false', () => {
    const report = createMockReport([createMockViolation()])
    const body = generatePrCommentBody(report, { showDetails: false })

    expect(body).not.toContain('<details>')
    expect(body).not.toContain('Top Violations')
  })

  it('includes commit SHA when provided', () => {
    const report = createMockReport([])
    const body = generatePrCommentBody(report, { commitSha: 'abc123def456' })

    expect(body).toContain('Commit:')
    expect(body).toContain('`abc123d`') // shortened to 7 chars
  })

  it('includes workflow name when provided', () => {
    const report = createMockReport([])
    const body = generatePrCommentBody(report, { workflowName: 'CI Pipeline' })

    expect(body).toContain('Workflow: CI Pipeline')
  })

  it('includes layerguard footer', () => {
    const report = createMockReport([])
    const body = generatePrCommentBody(report)

    expect(body).toContain('Generated by')
    expect(body).toContain('Layerguard')
  })

  it('shows "and X more" for many violations', () => {
    const violations: Violation[] = []
    for (let i = 0; i < 15; i++) {
      violations.push(createMockViolation({ sourceFile: `src/file${i}.ts` }))
    }
    const report = createMockReport(violations)
    const body = generatePrCommentBody(report, { showDetails: true })

    expect(body).toContain('10 of 15')
    expect(body).toContain('and 5 more')
  })
})

describe('detectPrNumber', () => {
  const originalEnv = process.env

  beforeEach(() => {
    vi.resetModules()
    process.env = { ...originalEnv }
  })

  afterEach(() => {
    process.env = originalEnv
  })

  it('returns undefined when no PR environment', () => {
    delete process.env.GITHUB_EVENT_PATH
    delete process.env.GITHUB_REF

    const prNumber = detectPrNumber()

    expect(prNumber).toBeUndefined()
  })

  it('detects PR number from GITHUB_REF', () => {
    delete process.env.GITHUB_EVENT_PATH
    process.env.GITHUB_REF = 'refs/pull/123/merge'

    const prNumber = detectPrNumber()

    expect(prNumber).toBe(123)
  })

  it('handles non-PR GITHUB_REF', () => {
    delete process.env.GITHUB_EVENT_PATH
    process.env.GITHUB_REF = 'refs/heads/main'

    const prNumber = detectPrNumber()

    expect(prNumber).toBeUndefined()
  })
})

describe('detectRepository', () => {
  const originalEnv = process.env

  beforeEach(() => {
    vi.resetModules()
    process.env = { ...originalEnv }
  })

  afterEach(() => {
    process.env = originalEnv
  })

  it('returns GITHUB_REPOSITORY', () => {
    process.env.GITHUB_REPOSITORY = 'owner/repo'

    const repo = detectRepository()

    expect(repo).toBe('owner/repo')
  })

  it('returns undefined when not set', () => {
    delete process.env.GITHUB_REPOSITORY

    const repo = detectRepository()

    expect(repo).toBeUndefined()
  })
})

describe('isGitHubActionsEnvironment', () => {
  const originalEnv = process.env

  beforeEach(() => {
    vi.resetModules()
    process.env = { ...originalEnv }
  })

  afterEach(() => {
    process.env = originalEnv
  })

  it('returns true when GITHUB_ACTIONS is true', () => {
    process.env.GITHUB_ACTIONS = 'true'

    const result = isGitHubActionsEnvironment()

    expect(result).toBe(true)
  })

  it('returns false when GITHUB_ACTIONS is not set', () => {
    delete process.env.GITHUB_ACTIONS

    const result = isGitHubActionsEnvironment()

    expect(result).toBe(false)
  })

  it('returns false when GITHUB_ACTIONS is false', () => {
    process.env.GITHUB_ACTIONS = 'false'

    const result = isGitHubActionsEnvironment()

    expect(result).toBe(false)
  })
})
