/**
 * GitHub integration for PR comments
 *
 * Posts violation summaries as PR comments using the `gh` CLI
 */

import { execSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import type { ViolationReport } from '../enforcer/violations.js'

/**
 * Options for posting a PR comment
 */
export interface GitHubCommentOptions {
  /**
   * PR number to comment on
   */
  prNumber?: number

  /**
   * Whether to update an existing comment instead of creating new
   */
  updateExisting?: boolean

  /**
   * Repository in owner/repo format (auto-detected if not provided)
   */
  repo?: string
}

/**
 * Result of posting a PR comment
 */
export interface GitHubCommentResult {
  /**
   * Whether the comment was posted successfully
   */
  success: boolean

  /**
   * Error message if failed
   */
  error?: string

  /**
   * URL of the comment if posted
   */
  commentUrl?: string
}

/**
 * Check if gh CLI is available
 */
export function isGhCliAvailable(): boolean {
  try {
    execSync('gh --version', { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

/**
 * Detect PR number from GitHub Actions environment
 */
export function detectPrNumber(): number | undefined {
  // GitHub Actions sets this for pull_request events
  const eventPath = process.env.GITHUB_EVENT_PATH
  if (eventPath) {
    try {
      const event = JSON.parse(readFileSync(eventPath, 'utf-8'))
      if (event.pull_request?.number) {
        return event.pull_request.number
      }
      if (event.number) {
        return event.number
      }
    } catch {
      // Ignore errors reading event file
    }
  }

  // Try GITHUB_REF for PR refs like refs/pull/123/merge
  const ref = process.env.GITHUB_REF
  if (ref) {
    const match = ref.match(/^refs\/pull\/(\d+)\//)
    if (match && match[1]) {
      return parseInt(match[1], 10)
    }
  }

  return undefined
}

/**
 * Detect repository from GitHub Actions environment
 */
export function detectRepository(): string | undefined {
  return process.env.GITHUB_REPOSITORY
}

/**
 * Generate markdown comment body for a violation report
 */
export function generatePrCommentBody(report: ViolationReport, options: {
  showDetails?: boolean
  commitSha?: string
  workflowName?: string
} = {}): string {
  const { showDetails = true, commitSha, workflowName } = options
  const status = report.passed ? '✅ Passed' : '❌ Failed'

  let md = `## Archgate Architecture Check ${status}\n\n`

  // Summary table
  md += `| Metric | Count |\n`
  md += `|--------|-------|\n`
  md += `| Errors | ${report.severityCounts.error} |\n`
  md += `| Warnings | ${report.severityCounts.warn} |\n`
  md += `| Total Violations | ${report.counts.total} |\n\n`

  // Violations by type
  if (report.counts.total > 0) {
    md += `### Violations by Type\n\n`
    const types = ['flow', 'isolation', 'circular', 'unlayered', 'depth', 'publicApi', 'dependentBudget', 'importCount', 'unmapped'] as const
    const typeEmoji: Record<string, string> = {
      flow: '🚫',
      isolation: '🔒',
      circular: '🔄',
      unlayered: '📦',
      depth: '📊',
      publicApi: '🔐',
      dependentBudget: '⚖️',
      importCount: '📈',
      unmapped: '❓',
    }
    for (const type of types) {
      const count = report.counts[type]
      if (count > 0) {
        md += `- ${typeEmoji[type] || ''} **${type}**: ${count}\n`
      }
    }
    md += '\n'
  }

  // Top violations
  if (showDetails && report.violations.length > 0) {
    md += `<details>\n<summary>Top Violations (${Math.min(10, report.violations.length)} of ${report.violations.length})</summary>\n\n`
    const topViolations = report.violations.slice(0, 10)
    for (const v of topViolations) {
      const line = v.line ? `:${v.line}` : ''
      md += `- \`${v.sourceFile}${line}\`: ${v.message}\n`
    }
    if (report.violations.length > 10) {
      md += `\n*...and ${report.violations.length - 10} more*\n`
    }
    md += `\n</details>\n\n`
  }

  // Footer with metadata
  md += `---\n`
  if (commitSha) {
    md += `Commit: \`${commitSha.substring(0, 7)}\`\n`
  }
  if (workflowName) {
    md += `Workflow: ${workflowName}\n`
  }
  md += `\n*Generated by [Archgate](https://github.com/caprado/archgate)*`

  return md
}

/**
 * Find existing Archgate comment on a PR
 */
function findExistingComment(prNumber: number, repo?: string): string | undefined {
  try {
    const repoArg = repo ? `--repo ${repo}` : ''
    const result = execSync(
      `gh pr view ${prNumber} ${repoArg} --json comments --jq '.comments[] | select(.body | contains("Archgate Architecture Check")) | .id' | head -1`,
      { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] }
    )
    const commentId = result.trim()
    return commentId || undefined
  } catch {
    return undefined
  }
}

/**
 * Post a comment to a GitHub PR
 */
export function postPrComment(
  report: ViolationReport,
  options: GitHubCommentOptions = {}
): GitHubCommentResult {
  const { updateExisting = true, repo = detectRepository() } = options
  let { prNumber } = options

  // Try to detect PR number if not provided
  if (!prNumber) {
    prNumber = detectPrNumber()
  }

  if (!prNumber) {
    return {
      success: false,
      error: 'No PR number provided and could not detect from environment. Use --pr-number or run in a GitHub Actions PR workflow.',
    }
  }

  // Check if gh CLI is available
  if (!isGhCliAvailable()) {
    return {
      success: false,
      error: 'GitHub CLI (gh) is not installed or not in PATH. Install from https://cli.github.com/',
    }
  }

  try {
    const bodyOptions: Parameters<typeof generatePrCommentBody>[1] = {
      showDetails: true,
    }
    if (process.env.GITHUB_SHA) {
      bodyOptions.commitSha = process.env.GITHUB_SHA
    }
    if (process.env.GITHUB_WORKFLOW) {
      bodyOptions.workflowName = process.env.GITHUB_WORKFLOW
    }
    const body = generatePrCommentBody(report, bodyOptions)

    const repoArg = repo ? `--repo ${repo}` : ''

    // Check for existing comment to update
    if (updateExisting) {
      const existingCommentId = findExistingComment(prNumber, repo)
      if (existingCommentId) {
        // Update existing comment
        execSync(
          `gh api repos/${repo}/issues/comments/${existingCommentId} --method PATCH --field body="${body.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`,
          { stdio: 'ignore' }
        )
        return {
          success: true,
          commentUrl: `https://github.com/${repo}/pull/${prNumber}#issuecomment-${existingCommentId}`,
        }
      }
    }

    // Create new comment
    // Use heredoc for multiline body
    const result = execSync(
      `gh pr comment ${prNumber} ${repoArg} --body-file -`,
      {
        input: body,
        encoding: 'utf-8',
        stdio: ['pipe', 'pipe', 'pipe'],
      }
    )

    return {
      success: true,
      commentUrl: result.trim() || `https://github.com/${repo}/pull/${prNumber}`,
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    return {
      success: false,
      error: `Failed to post PR comment: ${message}`,
    }
  }
}

/**
 * Check if we're running in a GitHub Actions environment
 */
export function isGitHubActionsEnvironment(): boolean {
  return process.env.GITHUB_ACTIONS === 'true'
}
